### ISSUE TITLE
Сформулировать ТЗ для дизайна и функционала DistributionUC

### ISSUE THREAD

**Issue by Leonid-Chromium** [Leonid-Chromium/Dispatcher-V3#23]
Продумать 
Что должен делать этот элемент
Как должен работать этот элемент
Как должен выглядеть этот элемент

**Comment by Leonid-Chromium** [comment]
### **Что должен делать этот элемент**

Элемент - User Control

Его основная задача - предоставить метод для компьютерного расчёта _оптимального_ (или хотя-бы близкого к оптимальному) графика реализации партий. на нём должно быть наглядно какой станок когда и сколько какую партию должен обрабатывать.
Расчёт времени должен быть основан на том,

- на какой операции находится партия
- какое время им нужно ещё для завершения этой операции
- сколько времени должно отдаваться на транспортировку между операциями
- рабочие ли станки
- есть ли кому работать на этой операции
- сколько времени затрачивается на операцию

Расчёт может проводиться долго и это стоит учитывать. Как минимум стоит вывести его (Расчёт) в отдельный поток.

**Comment by Leonid-Chromium** [comment]
### **Как должен работать этот элемент**

Расчёт проводится как минимум в отдельном потоке. Желательно сделать его асинхронным.

Сам алгоритм расчёта находится в отдельной библиотеке. В приложении через библиотеку SQLLib получаем необходимую информацию о станках, людях и партиях в виде DataTable и передаём в интересующий нас метод.

Алгоритм метода (назовём его аналоговым методом расчёта графика пластин) схож с уже реализованным дискретным, но необходимо учитывать время затрачиваемое на операцию написанное формулой, хранить график нужно не в виде таблицы станок * отрезки времени, а как список где каждая строчка описывает всё об одной операции над одной конкретной партией.

**Comment by Leonid-Chromium** [comment]
### **Как должен выглядеть этот элемент**

Набросок от руки
![photo_2022-02-28_11-04-39](https://user-images.githubusercontent.com/58108494/155922221-d6edbcbb-45c9-4c4f-b97e-d3edd27dafbc.jpg)

Нужно доработать набросок и перенести в Figma

**Comment by Daria-Liukshenko** [comment]
В  главном меню расположены:
- кнопка "назад";
- кнопка "настройки";
- строка поиска.
В панели навигации указаны номера станков.
Во временной линии указано время длительности станков.

**Comment by Leonid-Chromium** [comment]
Всё написано на бумаге.
Переводить это некому да и незачем.
пока...
